config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  get '/dashboard', to: 'rooms#dashboard', as: 'dashboard'
  get '/rooms/:id/chat', to: 'rooms#room'
  devise_for :doctors
  get '/doctors/:id/profile', to: 'doctors#profile' 
  devise_for :patients
  get '/patients/:id/profile', to: 'patients#profile' 
  get '/doctors', to: 'doctors#index' 
  get '/doctors/editinfo', to: 'doctors#editinfo' 
  put '/doctors/update', to: 'doctors#update' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root controller: :patients, action: :login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
end

# class Doctor::ParameterSanitizer < Devise::ParameterSanitizer
#   def initialize(*)
#     super
#     permit(:sign_up, keys: [:username, :email, :last_name, :first_name, :gender])
#   end
# end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room, inverse_of: :messages
  belongs_to :patient
  belongs_to :doctor
  
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, 
    dependent: :destroy, 
    inverse_of: :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :first_name, :last_name, :birthday, :gender])
    end

    def after_sign_in_path_for(resource)
        if current_patient
            "/patients/#{current_patient.id}/profile" # your path
        elsif current_doctor
            "/doctors/#{current_doctor.id}/profile"
        else
            "/"
        end
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    before_action :authenticate_doctor!
    def profile
        if doctor_signed_in?
            @doctor = current_doctor
        end
    end

    def index
        @doctors = Doctor.all
    end
    
    def editinfo
        @doctor = current_doctor
    end

    def update
        @doctor = current_doctor
        @doctor.update(update_params)
        flash[:notice] = "#{@doctor.username} profile was successfully updated."
        redirect_to "/doctors/#{@doctor.id}/profile"
    end
    

    private
    # Making "internal" methods private is not required, but is a common practice.
    # This helps make clear which methods respond to requests, and which ones do not.
    def update_params
      params.require(:doctor).permit(:last_name, :first_name, :gender, :birthday)
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :load_entities
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token
  
    def create
      # TODO change this line
      @room_message = Message.create patient: current_patient || Patient.find(1),
                                     doctor: current_doctor || Doctor.find(1),
                                     room: @room,
                                     message: params.dig(:message, :message) || params
      RoomChannel.broadcast_to @room, @room_message
    end
  
    protected
  
    def load_entities
      @room = Room.find params.dig(:message, :room_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :authenticate_patient!
    def profile
        if patient_signed_in?
            @patient = current_patient
        end
    end

    def index
        @patient = Patient.all
    end

    def editinfo
        @patient = current_patient
    end

    def update
        @patient = current_patient
        @patient.update(update_params)
        flash[:notice] = "#{@patient.username} profile was successfully updated."
        redirect_to "/patients/#{@patient.id}/profile"
    end


    private
    # Making "internal" methods private is not required, but is a common practice.
    # This helps make clear which methods respond to requests, and which ones do not.
    def update_params
        params.require(:patient).permit(:last_name, :first_name, :gender, :birthday)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    # Loads:
    # @rooms = all rooms
    # @room = current room when applicable
    before_action :load_entities

    def index
        @rooms = Room.all
    end

    def dashboard
        @rooms = Room.all
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new permitted_parameters

        if @room.save
        flash[:success] = "Room #{@room.name} was created successfully"
        redirect_to '/dashboard'
        else
        render :new
        end
    end

    def edit
    end

    def update
        if @room.update_attributes(permitted_parameters)
        flash[:success] = "Room #{@room.name} was updated successfully"
        redirect_to '/dashboard'
        else
        render :new
        end
    end

    def show
        @room_message = Message.new room: @room
        # TODO: change this line
        @room_messages = @room.messages.includes(:patient)
    end

    protected

    def load_entities
        @rooms = Room.all
        @room = Room.find(params[:id]) if params[:id]
    end

    def permitted_parameters
        params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_url(user)
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        url = "https://gravatar.com/avatar/#{gravatar_id}.png"
      end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/doctors/editinfo.html.erb
<h2>Edit Profile</h2>

<%= simple_form_for(@doctor, url: '/doctors/update', html: { method: :put }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <%= f.input :last_name%>
        <%= f.input :first_name %>
        <%= f.input :gender, required: true,
              collection: ['Female','Male', 'Unavailable'] %>
        <%= f.input :birthday, as: :date, start_year: Date.today.year - 90, discard_hour: true,
                end_year: Date.today.year - 12, order: [:month, :day, :year]  %>
    </div>
    </br>
    <div class="form-actions">
    <%= f.button :submit, "Update", :class => 'btn btn-primary col-1'%>
    </div>
<% end %>
</br>
<div>
  <%= link_to "Back", :back %>
</div>

app/views/doctors/index.html.erb
<h2>All Doctors</h2>

app/views/doctors/profile.html.erb
<h1>Doctor Profile</h1>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
   </div>
 <% end %>
<% end %>
<a href="/dashboard">Rooms</a>

<ul id="details">
  <li>
    Username:
    <%= @doctor.username %>
  </li>
  <li>
    Email:
    <%= @doctor.email %>
  </li>
  <li>
    Name:
    <%= @doctor.first_name + " " + @doctor.last_name %>
  </li>
  <li>
    Gender:
    <%= @doctor.gender %>
  </li>
  <li>
    Birthday:
    <%= @doctor.birthday.strftime("%B %d, %Y") %>
  </li>
</ul>

<div class="row">
  <%= link_to 'Edit Info', '/doctors/editinfo', :class => 'btn btn-primary col-2' %>
  <%= link_to 'Change Password or Delete', '/doctors/edit', :class => 'btn btn-danger col-2' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Healthcare Consulting System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'ohcs' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
        <%= render partial: 'shared/navigation_bar' %>
          <div class="my-3">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/patients/editinfo.html.erb
<h2>Edit Profile</h2>

<%= simple_form_for(@patient, url: '/patients/update', html: { method: :put }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :last_name%>
    <%= f.input :first_name %>
    <%= f.input :gender, required: true,
                collection: ['Female','Male', 'Unavailable'] %>
    <%= f.input :birthday, as: :date, start_year: Date.today.year - 90, discard_hour: true,
                end_year: Date.today.year - 12, order: [:month, :day, :year]  %>
  </div>
  </br>
  <div class="form-actions">
    <%= f.button :submit, "Update", :class => 'btn btn-primary col-1'%>
  </div>
<% end %>
</br>
<div>
  <%= link_to "Back", :back %>
</div>

app/views/patients/index.html.erb
<h2>All Patients</h2>

app/views/patients/login.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
   </div>
 <% end %>
<% end %>
<a href="/patients/sign_in">Patient Login</a>
<br>
<a href="/doctors/sign_in">Doctor Login</a>

app/views/patients/profile.html.erb
<h1>Patient Profile</h1>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<a href="/dashboard">Rooms</a>

<ul id="details">
  <li>
    Username:
    <%= @patient.username %>
  </li>
  <li>
    Email:
    <%= @patient.email %>
  </li>
  <li>
    Name:
    <%= @patient.first_name + " " + @patient.last_name %>
  </li>
  <li>
    Gender:
    <%= @patient.gender %>
  </li>
  <li>
    Birthday:
    <%= @patient.birthday.strftime("%B %d, %Y") %>
  </li>
</ul>

<div class="row">
  <%= link_to 'Edit Info', '/patients/editinfo', :class => 'btn btn-primary col-2' %>
  <%= link_to 'Change Password or Delete', '/patients/edit', :class => 'btn btn-danger col-2' %>
</div>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

app/views/rooms/dashboard.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <div class="mb-3">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        Create a room
      <% end %>
    </div>

    <% if @rooms.present? %>
      <nav class="nav flex-column">
        <% @rooms.each do |room| %>
          <%= link_to room.name, room_path(room), class: "nav-link room-nav-link" %>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no rooms
      </div>
    <% end %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the OHCS!
      </h4>

      <p>
        You can set up an appointment
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
</div>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<h1>Rooms index</h1>
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the RailsChatTutorial!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <img src="<%= gravatar_url(room_message.patient) %>" class="avatar" alt="">
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>
<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="#">OHCS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_patient %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= gravatar_url(current_patient) %>">
        <%= current_patient.username %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= button_to 'Profile', "/patients/#{current_patient.id}/profile", method: :get, class: 'dropdown-item' %>
        <%= button_to 'Logout', destroy_patient_session_url, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>

    <% if current_doctor %>
    <div class="dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= gravatar_url(current_doctor) %>">
        <%= current_doctor.username %>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= button_to 'Profile', "/doctors/#{current_doctor.id}/profile", method: :get, class: 'dropdown-item' %>
        <%= button_to 'Logout', destroy_doctor_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
    </div>
    <% end %>
</nav>